# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240307-025145-formal-cube

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en


pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"  # or any other Spacy model you want to use
  - name: SpacyTokenizer
  - name: RegexFeaturizer
    "case_sensitive": True
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    # Name of the language model to use
    model_name: "bert"
    # Pre-Trained weights to be loaded
    model_weights: "rasa/LaBSE"
    #cache_dir: null
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    ranking_length: 5
  
    constrain_similarities: true
  - name: "EntitySynonymMapper"
  # - name: ResponseSelector
  #   epochs: 100
  #   constrain_similarities: true
  # - name: FallbackClassifier
  #   threshold: 0.2
  #   ambiguity_threshold: 0.1


policies: #null # No configuration for policies was provided. The following default policies were used to train your model.
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.2
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 150
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    use_gpu: true
